<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class FileTypeIconController extends Controller
{
    
    public function getIconClassNames($extension) 
    {
    	$extensions = [
            'txt' => 'fa fa-file-text-o',
            'sxw' => 'fa fa-file-text-o',
            'rtf' => 'fa fa-file-text-o',
            'log' => 'fa fa-file-text-o',

            'jpg' => 'fa fa-file-image-o',
            'jpeg' => 'fa fa-file-image-o',
            'png' => 'fa fa-file-image-o',
            'gdraw' => 'fa fa-file-image-o',
            'psd' => 'fa fa-file-image-o',
            'gif' => 'fa fa-file-image-o',
            'tif' => 'fa fa-file-image-o',
            'bmp' => 'fa fa-file-image-o',
            'wmf' => 'fa fa-file-image-o',
            'emf' => 'fa fa-file-image-o',
            'ico' => 'fa fa-file-image-o',

            'm4a' => 'fa fa-file-audio-o',
            'm4p' => 'fa fa-file-audio-o',
            'wav' => 'fa fa-file-audio-o',
            'mp3' => 'fa fa-file-audio-o',
            'raw' => 'fa fa-file-audio-o',
            'bwf' => 'fa fa-file-audio-o',
            'aiff' => 'fa fa-file-audio-o',
            'au' => 'fa fa-file-audio-o',
            'ape' => 'fa fa-file-audio-o',
            'la' => 'fa fa-file-audio-o',
            'acc' => 'fa fa-file-audio-o',
            'aac' => 'fa fa-file-audio-o',
            'wma' => 'fa fa-file-audio-o',
            'swa' => 'fa fa-file-audio-o',
            'vox' => 'fa fa-file-audio-o',
            'voc' => 'fa fa-file-audio-o',
            'niff' => 'fa fa-file-audio-o',
            'asx' => 'fa fa-file-audio-o',
            'm3u' => 'fa fa-file-audio-o',
            'pls' => 'fa fa-file-audio-o',

            'mp4' => 'fa fa-file-video-o',
            'avi' => 'fa fa-file-video-o',
            'mov' => 'fa fa-file-video-o',
            'wmv' => 'fa fa-file-video-o',
            'mng' => 'fa fa-file-video-o',
            'qt' => 'fa fa-file-video-o',
            'wlmp' => 'fa fa-file-video-o',
            'aaf' => 'fa fa-file-video-o',
            '3gp' => 'fa fa-file-video-o',
            'asf' => 'fa fa-file-video-o',
            'avchd' => 'fa fa-file-video-o',
            'cam' => 'fa fa-file-video-o',
            'collab' => 'fa fa-file-video-o',
            'dat' => 'fa fa-file-video-o',
            'dvr-ms' => 'fa fa-file-video-o',
            'flv' => 'fa fa-file-video-o',
            'm1v' => 'fa fa-file-video-o',
            'm2v' => 'fa fa-file-video-o',
            'fla' => 'fa fa-file-video-o',
            'flr' => 'fa fa-file-video-o',
            'sol' => 'fa fa-file-video-o',
            'm4v' => 'fa fa-file-video-o',
            'mkv' => 'fa fa-file-video-o',
            'wrap' => 'fa fa-file-video-o',
            'mpeg' => 'fa fa-file-video-o',
            'mpg' => 'fa fa-file-video-o',
            'mpe' => 'fa fa-file-video-o',
            'mxf' => 'fa fa-file-video-o',
            'nsv' => 'fa fa-file-video-o',
            'ogg' => 'fa fa-file-video-o',
            'rm' => 'fa fa-file-video-o',
            'svi' => 'fa fa-file-video-o',
            'swf' => 'fa fa-file-video-o',
            'wtv' => 'fa fa-file-video-o',

            'php' => 'fa fa-file-code-o',
            'htm' => 'fa fa-file-code-o',
            'html' => 'fa fa-file-code-o',
            'mht' => 'fa fa-file-code-o',

            'xls' => 'fa fa-file-excel-o',
            'xlsm' => 'fa fa-file-excel-o',
            'xlsx' => 'fa fa-file-excel-o',
            'xlt' => 'fa fa-file-excel-o',
            'xltx' => 'fa fa-file-excel-o',
            'xltm' => 'fa fa-file-excel-o',
            'xlsm' => 'fa fa-file-excel-o',
            'xlsb' => 'fa fa-file-excel-o',
            'csv' => 'fa fa-file-excel-o',
            'tsv' => 'fa fa-file-excel-o',
            'xml' => 'fa fa-file-excel-o',
            'xla' => 'fa fa-file-excel-o',
            'xlam' => 'fa fa-file-excel-o',
            'prn' => 'fa fa-file-excel-o',

            'ppt' => 'fa fa-file-powerpoint-o',
            'pps' => 'fa fa-file-powerpoint-o',
            'ppsx' => 'fa fa-file-powerpoint-o',
            'ppsm' => 'fa fa-file-powerpoint-o',
            'pptx' => 'fa fa-file-powerpoint-o',
            'ppa' => 'fa fa-file-powerpoint-o',
            'ppam' => 'fa fa-file-powerpoint-o',
            'odp' => 'fa fa-file-powerpoint-o',
            'gslides' => 'fa fa-file-powerpoint-o',
            'key' => 'fa fa-file-powerpoint-o',
            'keynote' => 'fa fa-file-powerpoint-o',
            'nb' => 'fa fa-file-powerpoint-o',
            'nbp' => 'fa fa-file-powerpoint-o',
            'otp' => 'fa fa-file-powerpoint-o',
            'pez' => 'fa fa-file-powerpoint-o',
            'prz' => 'fa fa-file-powerpoint-o',
            'sdd' => 'fa fa-file-powerpoint-o',
            'shf' => 'fa fa-file-powerpoint-o',
            'show' => 'fa fa-file-powerpoint-o',
            'shw' => 'fa fa-file-powerpoint-o',
            'slp' => 'fa fa-file-powerpoint-o',
            'sspss' => 'fa fa-file-powerpoint-o',
            'sti' => 'fa fa-file-powerpoint-o',
            'sxi' => 'fa fa-file-powerpoint-o',
            'thmx' => 'fa fa-file-powerpoint-o',
            'watch' => 'fa fa-file-powerpoint-o',
            'potx' => 'fa fa-file-powerpoint-o',
            'potm' => 'fa fa-file-powerpoint-o',
            'pot' => 'fa fa-file-powerpoint-o',

            'doc' => 'fa fa-file-word-o',
            'docx' => 'fa fa-file-word-o',
            'abw' => 'fa fa-file-word-o',
            'docm' => 'fa fa-file-word-o',
            'dot' => 'fa fa-file-word-o',
            'dotx' => 'fa fa-file-word-o',
            'egt' => 'fa fa-file-word-o',
            'epub' => 'fa fa-file-word-o',
            'gdoc' => 'fa fa-file-word-o',
            'hwp' => 'fa fa-file-word-o',
            'hwpml' => 'fa fa-file-word-o',
            'lwp' => 'fa fa-file-word-o',
            'mcw' => 'fa fa-file-word-o',
            'mobi' => 'fa fa-file-word-o',
            'mbp' => 'fa fa-file-word-o',
            'md' => 'fa fa-file-word-o',
            'odm' => 'fa fa-file-word-o',

            'pdf' => 'fa fa-file-pdf-o',
            'ai' => 'fa fa-file-pdf-o',
            'ave' => 'fa fa-file-pdf-o',
            'cdr' => 'fa fa-file-pdf-o',
            'dtp' => 'fa fa-file-pdf-o',
            'indd' => 'fa fa-file-pdf-o',
            'pmd' => 'fa fa-file-pdf-o',
            'ppp' => 'fa fa-file-pdf-o',
            'pub' => 'fa fa-file-pdf-o',
            'qxd' => 'fa fa-file-pdf-o',

            'zip' => 'fa fa-file-zip-o',
            'rar' => 'fa fa-file-zip-o',
            'jar' => 'fa fa-file-zip-o',
            '7z' => 'fa fa-file-zip-o',
            'alz' => 'fa fa-file-zip-o',
            'cab' => 'fa fa-file-zip-o',
            'ace' => 'fa fa-file-zip-o',
            'apk' => 'fa fa-file-zip-o',
            'at3' => 'fa fa-file-zip-o',
            'arc' => 'fa fa-file-zip-o',
            'arj' => 'fa fa-file-zip-o',
            'b' => 'fa fa-file-zip-o',
            'ba' => 'fa fa-file-zip-o',
            'bin' => 'fa fa-file-zip-o',
            'bkf' => 'fa fa-file-zip-o',
            'bzip2' => 'fa fa-file-zip-o',
            'egg' => 'fa fa-file-zip-o',
            'egt' => 'fa fa-file-zip-o',
            'ecab' => 'fa fa-file-zip-o',
            'ezip' => 'fa fa-file-zip-o',
            'ess' => 'fa fa-file-zip-o',
            'gzip' => 'fa fa-file-zip-o',
            'ipg' => 'fa fa-file-zip-o',
            'lbr' => 'fa fa-file-zip-o',
            'lzip' => 'fa fa-file-zip-o',
            'lz' => 'fa fa-file-zip-o',
            'par' => 'fa fa-file-zip-o',
            'pyk' => 'fa fa-file-zip-o',
            'uha' => 'fa fa-file-zip-o',
            'tar' => 'fa fa-file-zip-o',
            'tgz' => 'fa fa-file-zip-o',
            'gz' => 'fa fa-file-zip-o',
            'tar.gz' => 'fa fa-file-zip-o',
        ];

        return array_get($extensions,strtolower($extension),'fa fa-file-o');
    }
}
